### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by firstnecron** [firstnecron/tt-content-scraper#1]
**Command Line Interface and Dependency Management**
- [x] Project includes a package.json file containing dependencies to run 'node scraper.js'
- [x] Running 'npm install' installs relevant dependencies
- [x] (Extra) The 'scraper.js' file can be run with the 'npm start' command

**Folder Generation**
- [x] Program creates one 'data' folder if that folder doesn't already exist. If the folder does exist, the program does nothing.

**Research npm packages**
Chosen scraping and CSV packages meet the following requirements on npm:
- [x] 1,000 downloads
- [x] Updated in the last 6 months

**Crawling**
- [x] The project uses the 'http://shirts4mike.com/shirts.php' URL as an entry point to look through the links on the page to find 8 shrits

**Scraping and Saving Data**
- [x] Project scrapes the product title, price, image, and url, and all information is in the correct place
- [x] A CSV is successfully saved to the 'data' folder in this format: 'YYYY-MM-DD.csv'
- [x] Column headers are in this order: Title, Price, ImageURL, URL, Time

**Overwriting Data**
- [x] If the script is run twice, the program overwrites the data. The file contains the data from the second call.

**Error Handling**
- [x] The program displays a human-friendly error (not just the original error code) when it cannot connect to 'http://shirts4mike.com'
- [x] (Extra) Program logs errors in a 'scraper-error.log' file
- [x] (Extra) New errors append to the end of the file with a timestamp [Tue Feb 16 2016 13:00:55 GMT-0800 (PST)] <error message>
